test = {   'name': 'q6_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> organized_positions.num_columns == 2\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> organized_positions.num_rows == 22\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # Make sure that you have the correct column labels!\n>>> np.asarray(organized_positions.labels).item(1) != "Position Title identity"\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> # Make sure that you have the correct column labels!\n>>> np.asarray(organized_positions.labels).item(0)  != "ministry"\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> len(organized_positions.where('Ministry', 'Energy').column('Positions').item(0)) == 54\nTrue", 'hidden': False, 'locked': False},
                                   {'code': ">>> len(organized_positions.where('Ministry', 'Environment and Parks').column('Positions').item(0)) == 175\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
